/** 
 * CONFIDENTIAL HELLA  KGaA HUECK & CO. (HKG)
 *
 * This is an unpublished work of authorship, which contains trade secrets,
 * created in 2015. Hella KGaA Hueck & Co. owns all rights to this work and
 * intends to maintain it in confidence to preserve its trade secret status.
 * Hella KGaA Hueck & Co. reserves the right, under the copyright laws of
 * Germany or those of any other country that may have jurisdiction, to
 * protect this work as an unpublished work, in the event of an inadvertent or
 * deliberate unauthorized publication. Hella KGaA Hueck & Co. also reserves
 * its rights under all copyright laws to protect this work as a published
 * work, when appropriate. Those having access to this work may not copy it,
 * use it, modify it or disclose the information contained in it without the
 * written authorization of Hella KGaA Hueck & Co..
 */
 
/**
 * THIS FILE IS AUTOGENERATED FROM RHAPSODY
 * CHANGES ARE ONLY ALLOWED IN THE FUNCTIONBODY FOR ROUNDTRIP
 * 
 * Company            : Hella KGaA Hueck & Co., Lippstadt, Germany
 * Project            : Truck_MFL_Full_LED
 * ModelElment        : LightControl_class
 * GeneratedDate      : Mon, 2, Mar 2015 
 * GeneratedTime      : 4:09 W. Europe Standard Time PM 
 * GeneratedByUser    : kramda2
 * RhapsodyVersion    : 8.1.1         
 * HellaProfileVersion:1.436 
 * 
 * Model-Filename  : LightControl_SwPkg.sbs
 * Model-Revision  : 1.13
 * Model-Author    : Kramer Daniel kramda2 (kramda2)
 * Model-Date      : 2015/03/02 15:45:08MEZ
 * Model-State     : IN_WORK
 * 
 * Filename        : $Source: LightControl_class.c $
 * Revision        : $Revision: 1.7 $
 * Author          : $Author: Kramer Daniel kramda2 (kramda2) $
 * Date            : $Date: 2015/03/02 16:11:38MEZ $
 * Status          : $State: IN_WORK $
 */

#include "LightControl_class.h"
#include "ErrorHandler_class.h"
#include "LedVoltage_class.h"
#include "macrodriver.h"
#include "OperationDetection_class.h"


/*## package Truck_MFL_Full_LED_Pkg::Software_SwPkg::SubSystems_SwPkg::DirectionIndicator_SwPkg::LightControl_SwPkg */

/*## class LightControl_class */
/**
 * LedCount
 */
#define LedCount (6U)
/**
 * LedSlideTime
 */
#define LedSlideTime (200U)
/**
 * REGULATOR_LED1
 */
#define REGULATOR_LED1 P3_bit.no1
/**
 * LedBypassPort
 */
#define LedBypassPort P1
/**
 * LedState_enum
 */
typedef enum 
{
    LedAllOff = 0U, /**  */
    Led1On = 1U, /**  */
    Led2On = 2U, /**  */
    Led3On = 3U, /**  */
    Led4On = 4U, /**  */
    Led5On = 5U, /**  */
    LedAllOn = 6U /**  */
} LedState_enum;

static inline void LedState_incr(LedState_enum* ledState)
{
    *(uint8*)ledState++;
    if(LedAllOn < ledState) ledState = LedAllOff;
}

static inline void LedState_decr(LedState_enum* ledState)
{
    if(ledState > LedAllOff) *(uint8*)ledState--;
}

/**
 * LedBypass_enum
 */
typedef enum 
{
    NoLedBypass = 0x00U, /**  */
    BypassLed6 = 0x01U, /**  */
    BypassLeds5To6 = 0x03U, /**  */
    BypassLeds4To6 = 0x07U, /**  */
    BypassLeds3To6 = 0x47U, /**  */
    BypassLeds2To6 = 0xC7U /**  */
} LedBypass_enum;

/*## attribute LedSlideTimer */
static Timer_struct LedSlideTimer = {0U,1U};

/*## attribute LedState */
static LedState_enum LedState = LedAllOff;

/*## attribute LightControlState */
static LightControl_enum LightControlState = LedsOff;

/*## attribute SlideStepTime */
static const uint8 SlideStepTime = LedSlideTime/LedCount;

/*## attribute StabilizeCounter */
static uint8 StabilizeCounter = 0U;

/**
 * SetLedState(LedState_enum NewLedState)
 *
 * @return void
 *
 * @param LedState_enum NewLedState 
 * \description:According to the argument a new led state is set. 
 *  \resolution:N/A 
 *  \range_min:LedAllOff 
 *  \range_max:LedAllOn 
 *  \range_enum:{0U;6U} 
 *  \unit:N/A 
 * 
 */
/*## operation SetLedState(LedState_enum) */
static void SetLedState(LedState_enum NewLedState);

void LightControlCyclicTask(void)
{
    switch(LightControlState)
    {
      case FiveLedsOn : 
      {
        for(LedState = Led1On; LedState <= Led5On; LedState++)
        {
          SetLedState(LedState);
        }
        LedState--;
        LightControlState = CheckLedVoltageState;
        break;
      }
      default:
      {
        /* the default case should never be reached --> LightControlError  */
        LightControlState = LightControlError;
        break;
      }
    }
}

/*## operation SetLightControlMode(LightControl_enum) */
void SetLightControlMode(LightControl_enum Mode)
{
    /*#[ operation SetLightControlMode(LightControl_enum) */
    if( Mode == LedsOff )
    {
      /* reset purpose */
      LightControlState = LedsOff;
    }
    else if( LightControlState > SixLedSlide )
    {
      LightControlState = LightControlState;
    }
    else
    {
      LightControlState = Mode;
    }
    /*#]*/
}

/*## operation SetLedState(LedState_enum) */
static void SetLedState(LedState_enum NewLedState)
{
    /*#[ operation SetLedState(LedState_enum) */
    switch(NewLedState)
    {
      case LedAllOff : 
      {
        /* regulator */
        REGULATOR_LED1 = (0U);
        /* Led gates */
        LedBypassPort = BypassLeds2To6;
        LedState = LedAllOff;
        break;
      }
      
      case Led1On :
      {
        /* Led gates */
        LedBypassPort = BypassLeds2To6;
        /* regulator */
        REGULATOR_LED1 = (1U);
        LedState = Led1On;
        break;
      }
      
      case Led2On :
      { 
        /* Led gates */
        LedBypassPort = BypassLeds3To6;
        /* regulator */
        REGULATOR_LED1 = (1U);
        LedState = Led2On;
        break;
      }
      
      case Led3On :
      {
        /* Led gates */
        LedBypassPort = BypassLeds4To6;
        /* regulator */
        REGULATOR_LED1 = (1U);
        LedState = Led3On;
        break;
      }
    
      case Led4On :
      {
        /* Led gates */
        LedBypassPort = BypassLeds5To6;
        /* regulator */
        REGULATOR_LED1 = (1U);
        LedState = Led4On;
        break;
      }
    
      case Led5On :
      {
        /* Led gates */
        LedBypassPort = BypassLed6;
        /* regulator */
        REGULATOR_LED1 = (1U);
        LedState = Led5On;
        break;
      }
    
      case LedAllOn :
      { 
        /* Led gates */
        LedBypassPort = NoLedBypass;
        /* regulator */
        REGULATOR_LED1 = (1U);
        LedState = LedAllOn;
        break;
      }
      
      default :
      {
        /* the default case should never be reached --> LightControlError  */
        LightControlState = LightControlError;
        break;
      }  
    }
    /* delay Led voltage measurment about 15µs */
    Delay(_15us);
    
    MeasureLedVoltage(LedState);
    
    /*#]*/
}
